# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-production.yml
#
#
# URL of static site
url: "https://www.devicetree.org"
# Destination folder
destination: production.devicetree.org
# Production boolean used in layouts / includes
production: true
# Google Analytics
google_analytics:
  enabled: true
  code: GTM-P8JRM63
  cookies:
    necessary:
      - name: cookieControl
        description: >
          This is used to control the display of the preferences pop up. Without this, we wouldn't know if you've clicked Accept!
      - name: cookieControlPrefs
        description: >
          This is used to store your cookie preferences. Without this we wouldn't know which cookies you want!
    marketing:
      - name: _ga
        description: >
          2 years - Used to distinguish users.
      - name: _gid
        description: >
          24 hours - Used to distinguish users.
      - name: _gat
        description: >
          1 minute - Used to throttle request rate.
